apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-config
spec:
  hosts:
%{ for i, master in masters_info_list ~}
  - {name: ${master.hostname}, address: ${master.ipv4}, internalAddress: "${master.ipv4}%{ if enable_ipv6 },${master.ipv6}%{ endif }", user: masters${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
%{ for i, worker in workers_info_list ~}
  - {name: ${worker.hostname}, address: ${worker.ipv4}, internalAddress: "${worker.ipv4}%{ if enable_ipv6 },${worker.ipv6}%{ endif }",  user: workers${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
  roleGroups:
    etcd:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    master:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    worker:
%{ for worker in workers_info_list ~}
    - ${worker.hostname}
%{ endfor ~}
  kubernetes:
    apiserverCertExtraSans:
    - ${livirt_host_ip}
    disableKubeProxy: ${disable_kube_proxy}
    containerManager: containerd
    version: ${k8s_version}
    nodelocaldns: false
  network:
    plugin: none
    kubeServiceCIDR: ${kube_service_cidrs.ipv4}%{ if enable_ipv6 },${kube_service_cidrs.ipv6}%{ endif }
    kubePodsCIDR: ${kube_pods_cidrs.ipv4}%{ if enable_ipv6 },${kube_pods_cidrs.ipv6}%{ endif }
