apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-config
spec:
  hosts:
%{ for i, master in masters_info_list ~}
  - {name: ${master.hostname}, address: %{ if enable_ipv6 }${master.ipv6}%{ else }${master.ipv4}%{ endif }, user: masters${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
%{ for i, worker in workers_info_list ~}
  - {name: ${worker.hostname}, address: %{ if enable_ipv6 }${worker.ipv6}%{ else }${worker.ipv4}%{ endif }, user: workers${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
  roleGroups:
    etcd:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    master:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    worker:
%{ for worker in workers_info_list ~}
    - ${worker.hostname}
%{ endfor ~}
  kubernetes:
    apiserverCertExtraSans:
    - ${livirt_host_ip}
    containerManager: containerd
    disableKubeProxy: ${disable_kube_proxy}
    version: ${k8s_version}
    nodelocaldns: false
  network:
    plugin: none
    kubePodsCIDR: ${k8s_pod_cidr.ipv4}%{ if enable_ipv6 },${k8s_pod_cidr.ipv6}%{ endif }
    kubeServiceCIDR: ${k8s_service_cidr.ipv4}%{ if enable_ipv6 },${k8s_service_cidr.ipv6}%{ endif }
