apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-config
spec:
  hosts:
%{ for i, master in masters_info_list ~}
  - {name: ${master.hostname}, address: ${master.ipv4}, user: masters${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
%{ for i, worker in workers_info_list ~}
  - {name: ${worker.hostname}, address: ${worker.ipv4}, user: workers${i}, privateKeyPath: "~/.ssh/id_rsa"}
%{ endfor ~}
  roleGroups:
    etcd:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    master:
%{ for master in masters_info_list ~}
    - ${master.hostname}
%{ endfor ~}
    worker:
%{ for worker in workers_info_list ~}
    - ${worker.hostname}
%{ endfor ~}
  kubernetes:
    apiserverCertExtraSans:
    - ${livirt_host_ip}
    containerManager: containerd
    disableKubeProxy: ${disable_kube_proxy}
    version: ${k8s_version}
    nodelocaldns: false
  network:
    plugin: none
    kubeServiceCIDR: 172.16.0.0/16
